package com.codidevs.nutriapp.ui.navigation

object NutriRoutes {
    const val SPLASH = "splash"
    const val REGISTRO = "registro"
    const val IMC = "imc"
    const val MODULOS = "modulos"
    const val HOME = "home"
    const val SENDERO = "sendero"
    const val JUEGOS = "juegos"
    const val JUEGO_ARRASTRAR = "juego_arrastrar"
    const val JUEGO_VF = "juego_vf"
    const val JUEGO_COMPLETA = "juego_completa"
    const val JUEGO_MEJOR = "juego_mejor"
    const val JUEGO_RULETA = "juego_ruleta"
    const val JUEGO_MEMORIA = "juego_memoria"
    const val NIVEL_DETALLE = "nivel_detalle"
    const val ACTIVIDADES = "actividades"
    const val ACTIVIDAD = "actividad"
    const val ACTIVIDAD_DESCUBRE = "actividad_descubre"
    const val ACTIVIDAD_GRUPO = "actividad_grupo"
    const val ACTIVIDAD_VF = "actividad_vf"
    const val ACTIVIDAD_FRASE = "actividad_frase"
    const val ACTIVIDAD_MEJOR = "actividad_mejor"
    const val ACTIVIDAD_RULETA = "actividad_ruleta"
    const val ACTIVIDAD_MEMORIA = "actividad_memoria"
    const val ACTIVIDAD_DESCUBRE_N2 = "actividad_descubre_n2"
    const val ACTIVIDAD_VF_N2 = "actividad_vf_n2"
    const val ACTIVIDAD_FRASE_N2 = "actividad_frase_n2"
    const val ACTIVIDAD_MEJOR_N2 = "actividad_mejor_n2"
    const val ACTIVIDAD_QUIZ = "actividad_quiz"
    const val ACTIVIDAD_SEMAFORO = "actividad_semaforo"
    const val ACTIVIDAD_RETO = "actividad_reto"
    const val PREMIO = "premio"
    const val RECOMPENSAS = "recompensas"
    const val PERFIL = "perfil"
}
